# Generated by Django 3.0.7 on 2020-06-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200610_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_priority', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.ToDoPriority'),
        ),
    ]
