# Generated by Django 3.0.7 on 2020-06-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200611_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.ToDoPriority'),
        ),
    ]
